services:
  - type: web
    name: student-teacher-connect-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SESSION_NAME
        value: stc.sid
      - key: FRONTEND_URL
        sync: false
